### ISSUE TITLE
As dev, Checklist to start the project

### ISSUE THREAD

**Issue by Cervangirard** [unhcr-americas/surveyDesigner#3]
- [x] Fill in the Key Dates and the provisional calendar
- [x] Add each user to the project as a "Guest
- [x] Make sure the Board is ready:https://github.com/unhcr-americas/surveyDesigner/projects/1
- [x] Make sure the Wiki Home is ready:https://github.com/unhcr-americas/surveyDesigner/wiki/Home
- [x] Also indicate the method of sharing CR in the Client Welcome issue: NA
- [x] If necessary, perform the steps in "dev/dev_history.R". Most are already done.
